version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=development  # You can change this to "production" if needed
