# Generated by Django 4.2.3 on 2023-07-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParticalTaskApp', '0004_remove_friendrequest_is_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='name',
        ),
    ]
